# Generated by Django 3.1.3 on 2020-11-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumpage', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
